//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuktionsEntity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuktionsEntities : DbContext
    {
        public AuktionsEntities()
            : base("name=AuktionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KoebstilbudSet> KoebstilbudSet { get; set; }
        public virtual DbSet<KundeSet> KundeSet { get; set; }
        public virtual DbSet<SalgsudbudSet> SalgsudbudSet { get; set; }
    }
}
