//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuktionsEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KundeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KundeSet()
        {
            this.KoebstilbudSet = new HashSet<KoebstilbudSet>();
        }
    
        public string Navn { get; set; }
        public int Tlf { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KoebstilbudSet> KoebstilbudSet { get; set; }
    }
}
