//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuktionsEntity.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class SalgsudbudSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalgsudbudSet()
        {
            this.KoebstilbudSet = new HashSet<KoebstilbudSet>();
        }
    
        public int SalgsudbudId { get; set; }
        public string Type { get; set; }
        public int Maengde { get; set; }
        public System.DateTime Tidsfrist { get; set; }


        [NotMapped]
        public string Tidsfristen
        {
            get

            {
                if (Tidsfrist < DateTime.Now)
                {
                    return "Udløbet";

                }
                else
                {
                    return (DateTime.Now- Tidsfrist).ToString(@"dd\.hh\:mm\:ss");
                }
            }
            set { }
        }


        [NotMapped]
        public string HighestBidder
        {
            get
            {
                if (KoebstilbudSet.Count != 0)
                {
                    return KoebstilbudSet.Max(x => x.Pris)+"";
                }
                else
                {
                    return "Ingen bud";
                }
            }
            set { }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KoebstilbudSet> KoebstilbudSet { get; set; }
    }
}
